include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*gr.dart"
    - "lib/firebase_options.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
    - package:dart_code_metrics_presets/bloc.yaml
    - package:dart_code_metrics_presets/provider.yaml
    - package:dart_code_metrics_presets/flutter_hooks.yaml
    - package:dart_code_metrics_presets/intl.yaml
    - package:dart_code_metrics_presets/pub.yaml
    - package:dart_code_metrics_presets/metrics_recommended.yaml
    - recommended
  rules-exclude:
    - lib/bootstrap.dart
    - test/counter/cubit/counter_cubit_test.dart
    - test/counter/view/mock_counter_cubit.dart
  rules:
    - avoid-dynamic:
        exclude:
          - lib/app/app_bloc_observer.dart
    - prefer-match-file-name:
        exclude:
          - test/**
          - lib/l10n/**
    - avoid-shadowing:
        ignore-static: true
        ignore-fields: true
        ignore-parameters: true
    - avoid-nullable-interpolation:
        ignored-invocations:
          - log
          - print
          - debugPrint
          - v
          - t
          - d
          - i
          - w
          - e
          - wtf
          - f
    - avoid-ignoring-return-values:
        exclude:
          - lib/main_development.dart
          - lib/main_production.dart
          - lib/main_staging.dart
          - test/**
    - no-magic-string:
        allow-only-once: true
        ignored-invocations:
          - log
          - print
          - debugPrint
          - v
          - t
          - d
          - i
          - w
          - e
          - wtf
          - f
        exclude:
          - test/**
    - prefer-static-class:
        ignore-private: true
        ignore-names:
          - bootstrap
          - (.*)Provider
          - use(.*)
    - parameters-ordering:
        ignore-overridden: true
        required: 'first'
        default: 'last'
    - arguments-ordering:
        last:
          - child
          - children
    - member-ordering:
        ignore-mixins: false
        ignore-extensions: false
        ignore-extension-types: false
        ignore-enums: false 
        order:
          - constructors
          - public-fields
          - private-fields
          - close-method
          - dispose-method
        widgets-order:
          - constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method 
          - build-method
        exclude:
          - lib/routes/app_router.dart
    - prefer-extracting-callbacks:
        allowed-line-count: 100
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-long-functions:
        max-length: 200
    - dispose-fields:
        ignore-blocs: true
    - no-equal-arguments:
        ignored-parameters:
          - height
          - width
          - borderSide
          - left
          - right
          - bottom
          - top
          - vertical
          - horizontal
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 5
    - avoid-similar-names:
        show-similarity: true
        similarity-threshold: 0.9

  formatter:
    indent: 0
    line-length: 80
    cascading-widget-extensions: true

