include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*gr.dart"
    - "lib/firebase_options.dart"
    - "lib/firebase_options_dev.dart"
    - "lib/firebase_options_stg.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
    - package:dart_code_metrics_presets/bloc.yaml
    - package:dart_code_metrics_presets/provider.yaml
    - package:dart_code_metrics_presets/flutter_hooks.yaml
    - package:dart_code_metrics_presets/intl.yaml
    - package:dart_code_metrics_presets/pub.yaml
    - package:dart_code_metrics_presets/metrics_recommended.yaml
    - recommended

  rules-exclude:
    - lib/bootstrap.dart

  metrics-exclude:
    - test/**
    - lib/main_development.dart
    - lib/main_production.dart
    - lib/main_staging.dart

  rules:
    - format-comment: false
    - avoid-dynamic:
        exclude:
          - lib/app/app_bloc_observer.dart
    - prefer-match-file-name:
        exclude:
          - test/**
          - lib/l10n/**
    - avoid-shadowing:
        ignore-static: true
        ignore-fields: true
        ignore-parameters: true
    - avoid-nullable-interpolation:
        ignored-invocations:
          - log
          - print
          - debugPrint
          - v
          - t
          - d
          - i
          - w
          - e
          - wtf
          - f
    - avoid-ignoring-return-values:
        exclude:
          - lib/main_development.dart
          - lib/main_production.dart
          - lib/main_staging.dart
          - test/**
    - no-magic-string:
        allow-only-once: true
        ignored-invocations:
          - log
          - print
          - debugPrint
          - v
          - t
          - d
          - i
          - w
          - e
          - wtf
          - f
        exclude:
          - test/**
    - prefer-static-class:
        ignore-private: true
        ignore-names:
          - bootstrap
          - (.*)Provider
          - use(.*)
    - parameters-ordering:
        ignore-overridden: true
    - member-ordering:
        exclude:
          - lib/routes/app_router.dart
        order:
          - constructors
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed
          - create
        allowed-line-count: 3
    - avoid-inferrable-type-arguments:
        ignored-invocations:
          - context.read
          - GetIt.I
          - watch
          - context.select
          - context.watch
    - prefer-overriding-parent-equality:
        exclude:
          - lib/form_inputs/**
    - avoid-unnecessary-nullable-return-type:
        exclude:
          - lib/form_inputs/**
       

  formatter:
    indent: 0
    line-length: 80
    cascading-widget-extensions: true