workflows:
  build:
    name: Flutter Build and Analyze (with Flavors)

    environment:
      # Define any environment variables needed by your app or build process
      vars:
        FLUTTER_ANALYZER_ADDITIONAL_OPTIONS: '--fatal-warnings'  # Adjust if needed for very_good_analysis

      # Specify Flutter, Xcode, and other tools versions
      flutter: stable
      xcode: latest
      # Add other tools and their versions as needed (e.g., cocoapods, node, npm)

    cache:
      cache_paths:
        - $HOME/.gradle/caches  # Gradle cache
        - $FLUTTER_ROOT/.pub-cache  # Flutter package cache
        - $HOME/Library/Caches/CocoaPods  # Optional: Remove if causing issues
        - $CM_BUILD_DIR/node_modules

    triggering:
      events:
        - push
        - pull_request
        - pull_request_labeled  # GitHub only
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true  # Cancel outdated builds

    scripts:
      - name: Analyze Flutter code
        script: flutter analyze
      - name: Get Flutter packages
        script: flutter packages pub get

      # Build scripts for each flavor (modify main Dart file paths as needed)
      - name: Build APK for development flavor
        script: flutter build apk --debug  --split-per-abi --no-tree-shake-icons --flavor development  -t lib/main_development.dart
      - name: Build APK for staging flavor
        script: flutter build apk --debug  --split-per-abi --no-tree-shake-icons --flavor stage  -t lib/main_stage.dart
      - name: Build APK for production flavor
        script: flutter build apk --debug  --split-per-abi --no-tree-shake-icons --flavor production  -t lib/main_production.dart


      - name: Build app bundle for release (all flavors)
        script: |  # Multi-line script for app bundle (modify main Dart file paths as needed)
          flutter build appbundle --release -t lib/main_development.dart
          flutter build appbundle --release -t lib/main_staging.dart
          flutter build appbundle --release -t lib/main_production.dart
      - name: Build for iOS
        script: flutter build ios

    artifacts:
      # Include artifacts for each flavor and app bundle
      - build/**/outputs/apk/development/**/*.apk
      - build/**/outputs/apk/staging/**/*.apk
      - build/**/outputs/apk/production/**/*.apk
      - build/**/outputs/**/*.aab
      - flutter_drive.log  # Optional, remove if not needed

    publishing:
    # Define any post-build publishing actions (e.g., email notifications)
