name: mimi_pokemon_app

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  semantic-pull-request:
    if: github.actor != 'dependabot[bot]'
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      setup: dart run build_runner build --delete-conflicting-outputs
      min_coverage: 0

